backtesting:
  commission: 0.001
  initial_capital: 100000
  slippage: 0.001
data:
  cache_dir: data/cache
  default_source: yahoo
  history_start: '2010-01-01'
logging:
  file_path: logs/trading_engine.log
  level: INFO
risk_management:
  max_drawdown: 0.25
  max_position_size: 0.1
  stop_loss: 0.02
  take_profit: 0.05
